# Measuring & Classifying Exponence

**NOTES**:
1. Definitions are still a little ad-hoc but the intuition all works
2. Measures still need need to implemented

A typology of exponence derived in set-theoretic terms making use of setmorph tools

In [1]:
import setmorph as sm

Data files:

In [2]:
zen_df = sm.read_paradigms("src/setmorph/testdata/sample-zen-out.csv")
ngkolmpu_df = sm.read_paradigms("src/setmorph/testdata/sample-ng-tense-out.csv")
nuer_df = sm.read_paradigms("src/setmorph/testdata/sample-nuer-out.csv")
arabic_df = sm.read_paradigms("src/setmorph/testdata/sample-ar-out.csv")
rus_df = sm.read_paradigms("src/setmorph/testdata/sample-rus-out.csv")
fr_df = sm.read_paradigms("src/setmorph/testdata/sample-fr-out.csv")
uniq_df = sm.read_paradigms("src/setmorph/testdata/unique_test.csv")

In [3]:
fr_features = sm.read_features("src/setmorph/testdata/fr_features.csv")
ng_features = sm.read_features("src/setmorph/testdata/ng_features.csv")
ar_features = sm.read_features("src/setmorph/testdata/ar_features.csv")
nuer_features = sm.read_features("src/setmorph/testdata/nuer_features.csv")
rus_features = sm.read_features("src/setmorph/testdata/rus_features.csv")
zen_features = sm.read_features("src/setmorph/testdata/zen_features.csv")

WARNING:root:The feature `mood` has a single value `ind`. No exponents of `ind` will be possible.
WARNING:root:The feature `tense` has a single value `prs`. No exponents of `prs` will be possible.
WARNING:root:The feature `voice` has a single value `act`. No exponents of `act` will be possible.
WARNING:root:The feature `case` has a single value `nom`. No exponents of `nom` will be possible.

## Delta

Delta is some feature based description of the distribution of a formative, $a$. It is a complete statement describing the cells where $a$ occurs. The total set of deltas for a formative can be considered the maximal knowledge of a speaker about the meaning/distribution of that formative.

- let $a$ be some formative 
- let $x$ be some set of features
- let $y$ be some cell in $\mathrm{dist}(a)$ 
- let $z$ be some cell in $\mathrm{cell}(\lambda)$ 

We can then define $\delta_a$ as
- some set of feature-sets, $\{ x_1, x_2, ... x_n \}$, such that: 

$$
\forall x \in \delta_a, \exists y, z \ (x \subseteq y, z) \\
\forall y, \exists x  \in \delta_a \ (y \supseteq x ) \\
\forall z \supseteq x, \exists y \supseteq x \ (z = y) 
$$

Which means:
1. All sets of features in $\delta_a$ are subsets of at least a cell which is in the distribution of $a$.
2. All cells in the distribution of $a$ are represented by a subset $x$ in $\delta_a$
3. All cells that are supersets of an $x$ in $\delta_a$ are in the distribution of $a$

## Simple exponence

a formatve, $a$, is said to be a *simple exponent* iff:

$$
\exists |\delta_a| = 1 \\
|x \in \delta_a| = 1 
$$

We start by computing all exponents relations once and for all:

In [4]:
exponents = sm.find_exponents(fr_df, fr_features)
exponents

,lexeme,tier,slot,formative,exponence,# of cells,dist_a
0,aller,segmental,0,al,"{(pst), (prs, 2pl), (1pl, prs)}",10,"{(1pl, pst), (pst, 3sg), (pst, 2pl), (ptcp, pr..."
1,aller,segmental,0,iʁ,{(fut)},6,"{(fut, 2pl), (fut, 3sg), (1pl, fut), (fut, 1sg..."
2,aller,segmental,0,v,"{(prs, 2sg), (3pl, prs), (prs, 1sg), (prs, 3sg)}",4,"{(prs, 2sg), (3pl, prs), (prs, 1sg), (prs, 3sg)}"
3,aller,segmental,1,E,"{(fut, 2pl), (inf), (prs, 2pl), (1sg), (pst, 3...",7,"{(fut, 2pl), (prs, 1sg), (fut, 1sg), (inf), (p..."
4,aller,segmental,1,a,"{(1pl, pst), (3sg), (2sg), (pst, 2pl)}",8,"{(1pl, pst), (fut, 3sg), (prs, 2sg), (prs, 3sg..."
...,...,...,...,...,...,...,...
240,touer,segmental,4,m,"{(1pl, pst)}",1,"{(1pl, pst)}"
241,touer,segmental,4,t,"{(pst, 2pl)}",1,"{(pst, 2pl)}"
242,touer,segmental,4,ɑ̃,{(ptcp)},1,"{(ptcp, prs)}"
243,touer,segmental,4,ɔ̃,"{(1pl, prs), (fut, 3pl), (1pl, fut)}",3,"{(1pl, prs), (fut, 3pl), (1pl, fut)}"
244,touer,segmental,4,ʁ,"{(pst, 3pl)}",1,"{(pst, 3pl)}"

In [5]:
simple = sm.classify_simple(exponents)
simple

### Syncretism

A formative $a$ is considered to be an example of syncretism iff:

$\neg\exists \delta_a : |\delta_a| = 1$

There does not exist a description of 'a', $\delta_a$, which has a cardinality of 1, i.e. one set of features.

In [6]:
dfsyn = sm.classify_syn(exponents)
dfsyn

**Measurement**

- Number of cells
- Number of 'sets' in minimal description

To be implemented:
- TODO: Ratio of values over length of a dimension, i.e. 2 cases out of 12 total (harder to do given current implementation.

### Cumulative exponence

A formative $a$ is considered an example of cumulative exponence iff:

$\neg\exists \delta_a : \forall x \in \delta_a, |x| = 1$

There does not exists a $\delta_a$ such that for all sets of features in $\delta_a$ they have a cardinality of 1.

In [7]:
max_dimensions = fr_df["celllist"].fillna("").apply(len).max()
cumulation = sm.classify_cumulation(exponents, max_dimensions)
cumulation

**Measurement**

- Longest cumulation: how many feature values get cumulated at most
- Longest cumulation / longest possible cumulation
- % cells cumulative - percentage of cells in dist(a) which must be described using cumulation (based on minimal descrition currently)
- % dimensions - length of longest cumulation / longest possible cumulation

## Unique exponence

For a given value, v:
There is only one formative for which its all its deltas must contain that value:

$\exists!a : \forall \delta_a, \exists x \in \delta_a \ (v \in x) $

alternatively:

$| \{  a : \forall \delta_a, \exists x \in \delta_a \ (v \in x) \} | = 1$

There exists exactly one $a$ such that all the descriptions of $a$, there exists a set in that description that contains that value.

In [8]:
uniq = sm.classify_unique(exponents)
uniq

          lexeme value  slot formative
3          aller   inf     1         E
7          aller  ptcp     2        ɑ̃
40        croire   1sg     4         E
41        croire   3sg     4         a
41        croire   2sg     4         a
48         cuire   inf     1         ʁ
50         cuire   1sg     3         E
51         cuire   3sg     3         a
51         cuire   2sg     3         a
59     engloutir   inf     1         ʁ
60     engloutir   1sg     2         E
61     engloutir   3sg     2         a
61     engloutir   2sg     2         a
68         finir   inf     1         ʁ
69         finir   1sg     2         E
70         finir   3sg     2         a
70         finir   2sg     2         a
77          haïr   inf     1         ʁ
78          haïr   1sg     2         E
79          haïr   3sg     2         a
79          haïr   2sg     2         a
85        lisser   inf     1         E
88        lisser   3sg     3         a
88        lisser   2sg     3         a
92        lisser  ptcp     4        ɑ̃
95        manger   inf     1         E
98        manger   3sg     3         a
98        manger   2sg     3         a
102       manger  ptcp     4        ɑ̃
127       mourir  ptcp     5        ɑ̃
133       partir   1sg     4         E
134       partir   3sg     4         a
134       partir   2sg     4         a
137       partir  ptcp     4        ɑ̃
155        peler   inf     3         E
162        peler  ptcp     6        ɑ̃
175      pouvoir  ptcp     6        ɑ̃
190     recevoir  ptcp     6        ɑ̃
193  reconvoquer   inf     1         E
201  reconvoquer  ptcp     3        ɑ̃
204    sonoriser   inf     1         E
212    sonoriser  ptcp     3        ɑ̃
218       sortir   1sg     4         E
219       sortir   3sg     4         a
219       sortir   2sg     4         a
222       sortir  ptcp     4        ɑ̃
225     squeezer   inf     1         E
228     squeezer   3sg     3         a
228     squeezer   2sg     3         a
232     squeezer  ptcp     4        ɑ̃
238        touer   inf     3         E
242        touer  ptcp     4        ɑ̃


### Verbose exponence

For a given value, v and some word $\omega$:

$$| \{  a \in \mathrm{wordform}(\omega): \forall \delta_a, \exists x \in \delta_a \ (v \in x) \} | > 1$ \\
$$

In [9]:
ve = sm.classify_verbose(exponents, fr_df)
ve[ve.lexeme == "lisser"]

,lexeme,cell,value,formatives,# formatives
248,lisser,fut.1pl,fut,"[(segmental, 1, Ø), (segmental, 2, ʁ), (segmen...",3
250,lisser,fut.1sg,fut,"[(segmental, 1, Ø), (segmental, 2, ʁ), (segmen...",3
252,lisser,fut.2pl,fut,"[(segmental, 1, Ø), (segmental, 2, ʁ), (segmen...",3
254,lisser,fut.2sg,fut,"[(segmental, 1, Ø), (segmental, 2, ʁ), (segmen...",3
256,lisser,fut.3pl,fut,"[(segmental, 1, Ø), (segmental, 2, ʁ), (segmen...",3
258,lisser,fut.3sg,fut,"[(segmental, 1, Ø), (segmental, 2, ʁ), (segmen...",3
265,lisser,pst.1pl,1pl,"[(segmental, 3, a), (segmental, 4, m)]",2
266,lisser,pst.1pl,pst,"[(segmental, 3, a), (segmental, 4, m)]",2
269,lisser,pst.2pl,2pl,"[(segmental, 3, a), (segmental, 4, t)]",2
270,lisser,pst.2pl,pst,"[(segmental, 3, a), (segmental, 4, t)]",2
273,lisser,pst.3pl,3pl,"[(segmental, 1, E), (segmental, 2, ʁ)]",2
274,lisser,pst.3pl,pst,"[(segmental, 1, E), (segmental, 2, ʁ)]",2

TODO: This is missing the word itself, can be added by merging with the original df.

**Measurement:**
    
- '# of formatives': number of formatives expressing that valuein a given word

To be implemented / further processing of the above dataframe:
- We could also do an average of formatives expressing a given value
- Number of cells where it is expressed verbose

### Allomorphy

This one is most problematic - still needs tweaking how it fits into the typology, how to measure and define.

There is more than one formative which expresses a given value and these don't co-occur.

For a given value, $v$, we see allomorphy if:

$$
\exists a, b : \forall \delta_a, \delta_b, \exists x \in \delta \ ( v \in x $ )\\
\{\Sigma \in \mathrm{dist}(a)| v \in \Sigma\} \neq \{\Sigma \in \mathrm{dist}(b)| v \in \Sigma\} $$

- There are two formatives which both have v in some $x$ in their exponent set
- With regard to this value $v$, they have different cells

Problems:
- overabundance: they'll have the exact same distribution, yet we want to call it allomorphy...
- For overabundance we need to say:
1. There exist two f

$$
| \{  a : \forall \delta_a, \exists x \in \delta_a \ (v \in x) \} | > 1 \\
\exists a_i,a_j : \{\Sigma \in \mathrm{dist}(a_i)| v \in \Sigma\} \neq \{\Sigma \in \mathrm{dist}(a_j)| v \in \Sigma\} 
$$

1. The number of formatives which have $v$ in all their deltas is more than one
2. There exist at least two formative which do not only occur in the same set of cells which contain $v$

In [10]:
allo = sm.classify_allomorphy(exponents, fr_df)
allo

,lexeme,vals,allomorph set,allomorph set count,cells with v,% allomorphs to cells containing v
0,aller,1pl,"{((segmental, 0, al),), ((segmental, 2, ɔ̃),),...",3,7,42.857143
1,aller,1sg,"{((segmental, 0, v),), ((segmental, 1, E),)}",2,6,33.333333
2,aller,2pl,"{((segmental, 0, al),), ((segmental, 1, E),), ...",3,7,42.857143
3,aller,2sg,"{((segmental, 0, v),), ((segmental, 1, a),)}",2,6,33.333333
4,aller,3pl,"{((segmental, 0, v),), ((segmental, 2, ɔ̃),), ...",3,7,42.857143
...,...,...,...,...,...,...
166,touer,3pl,"{((segmental, 4, ɔ̃),), ((segmental, 3, E), (s...",3,10,30.000000
167,touer,3sg,"{((segmental, 3, a),), ((segmental, 1, u),)}",2,9,22.222222
168,touer,fut,"{((segmental, 3, a),), ((segmental, 3, E),), (...",4,24,16.666667
169,touer,prs,"{((segmental, 4, ɔ̃),), ((segmental, 3, E),), ...",4,17,23.529412
170,touer,pst,"{((segmental, 2, w),), ((segmental, 4, t),), (...",6,21,28.571429

£**Measurement**

- '# of allomorphs'
- '% of allomorphs to cells containing v' - this can be greater than 100% under current implementation.

Examples:


| (a) SG|  | (b) SG |   | (c) SG |   | (d) SG |
|---|      |---|        |---|        |---|
|x|        | x  |       | x  |       | x  |
|y|        | xy |       | x  |       | x  |
|z|        |  y |       | xy |       | yz |

(e)
 | (d) SG | PL |
 |---|---|
| xy  | z |
| xy  | z |
| x  | y |


(a)
     exp(x) = {SG.1}
     exp(y) = {SG.2}
     exp(z) = {SG.3}

     This is allomorphy for singular

     real(SG) = {x, y, z}

(b) exp(x) = {SG.1, SG.2}
    exp(y) = {SG.2, SG.3}
    real(SG) = {x, y} OR {x, y, xy}

    The question is: Is the realization sensitive to words or not ?

The current implementation treats the analysis of 'allomorphy of singular' as:

- (a): x, y, z
- (b): x, y
- (c): x, y
- (d): x, yz

Another implementation might consider the following:

- (a): x, y, z
- (b): x, xy, y
- (c): x, xy
- (d): x, yz

## Higher-order exceptionality

See Carroll (2022)


To do:

- [ ] Tests for allomorphy + VE
- [ ] fix VE w overabundance
- [ ] fix allomorphy w overabundance
- [ ] change df in place, no deep copies
- [ ] prune feature structure to lexeme ? => tests, examples, note